const Translations = window.Translations || {
  GetString: key => ({
    app_name: 'AI Asset Workbench', app_eyebrow: 'Extract · Generate · Recompose', save_workspace: '保存工作区', export_png: '导出 PNG', project: '项目', upload_scene: '导入场景', upload_scene_hint: 'PNG / JPG / WEBP', add_reference: '添加参考图', add_reference_hint: '用于生成或比对', remove_scene: '移除场景', remove_reference: '移除参考图', workflow: '工作流', quality: '边缘质量', local: '本地', edge_quality: '当前评估', quality_hint: '本地遮罩可离线使用；配置 API 后可切换 AI 抠图。', step_isolate: '隔离元素', step_isolate_hint: '建立初始透明遮罩', step_refine: '精修边缘', step_refine_hint: '画笔补齐细枝与花瓣', step_generate: '生成变体', step_generate_hint: '保持风格与光照一致', step_place: '无痕还原', step_place_hint: '合成回原图并导出', tool_mask: '遮罩', tool_composite: '合成预览', tool_compare: '前后对比', zoom_out: '缩小画布', zoom_in: '放大画布', reset_view: '重置视图', undo: '撤销', redo: '重做', delete_mask: '删除当前遮罩', empty_title: '从一张图开始', empty_hint: '导入场景，或直接载入示例湖畔图。', load_demo: '载入示例', legend_selection: '保留区域', legend_feather: '羽化区域', isolation: '隔离', ai_ready: 'AI 就绪', auto_isolate: '自动抠图', clear_mask: '清除遮罩', invert_mask: '反选遮罩', brush_size: '画笔大小', edge_feather: '边缘羽化', brush_add: '添加', brush_remove: '移除', brush_mode: '遮罩画笔模式', generation: '生成', optional: '可选', prompt_label: '提示词', prompt_placeholder: '例如：同风格的一簇野花，暖色夕阳，透明背景', size_label: '尺寸', generate_image: '生成图像', generated_ready: '已生成预览', use_generated: '作为参考', composite: '合成', non_destructive: '非破坏', opacity: '不透明度', blend_mode: '混合模式', blend_normal: '正常', blend_multiply: '正片叠底', blend_screen: '滤色', composite_export: '导出合成图', assistant: 'AI 助手', local_ready: '就绪', assistant_welcome: '告诉我你想保留的元素，我会给出遮罩和生成建议。', chat_placeholder: '描述元素、风格或合成问题…', send_message: '发送消息', api_settings: 'API 设置', api_base_label: 'OpenAI 兼容地址', api_base_placeholder: 'https://api.openai.com/v1', api_key_label: 'API Key', api_key_placeholder: '仅保存在当前浏览器', api_settings_hint: '可接入 OpenAI、兼容网关或本地服务。未配置时使用本地演示模式。', scene_loaded: '场景已载入', reference_loaded: '参考图已载入', mask_ready: '遮罩已建立，可用画笔修正边缘。', mask_cleared: '遮罩已清除', mask_inverted: '遮罩已反选', undo_done: '已撤销上一步遮罩操作。', redo_done: '已重做遮罩操作。', delete_done: '当前遮罩已删除。', exported: 'PNG 已导出', composite_done: '合成图已导出', api_missing: '请先在 API 设置中填写地址与 Key。', generation_done: '生成完成，可设为参考图。', generation_failed: '生成失败，已保留当前工作区。', chat_failed: 'AI 暂不可用，请检查 API 设置。', saved: '工作区已保存到本机浏览器。', demo_loaded: '示例湖畔图已载入。', no_scene: '请先导入一张场景图。', local_mode: '本地演示模式', generating: '生成中…', thinking: '思考中…'
  })[key] || key
};
const pipelineStrings = { step_sam2: 'SAM 2 确定区域', step_sam2_hint: '框选或点击目标后确认', step_matte: 'Matte Anything 细化', step_matte_hint: '生成柔和 alpha 边缘', step_foreground: '原图像素前景', step_foreground_hint: '保留原始颜色与纹理', step_nano: 'Nano Banana 局部补全', step_nano_hint: '只修复被移除区域', step_depth: '按深度顺序合成', step_depth_hint: '前后景与光照一致', sam2_section: 'SAM 2 区域', sam2_checking: '检查 SAM 2', sam2_online: 'SAM 2 在线', sam2_offline: '本地 fallback', selection_mode: 'SAM 2 选择模式', selection_box: '框选', selection_point: '点击', selection_hint: '先在画布上框选或点击目标，再确认区域。', sam2_select: '确认 SAM 2 区域', matte_refine: 'Matte Anything 细化', foreground_section: '原图像素前景', pixel_locked: '像素锁定', foreground_hint: '从原图读取 RGB，只把透明度交给 matte，避免生成纹理漂移。', extract_foreground: '提取原图前景层', nano_section: 'Nano Banana 背景补全', local_fallback: '局部', nano_prompt_label: '补全提示', nano_prompt_placeholder: '只描述被移除区域的背景，不要改动前景元素', nano_provider_label: '服务通道', provider_tokenx24: 'TokenX24', provider_visionary: 'Visionary', nano_repair: '只补全背景洞口', composite: '深度合成', depth_order: '深度顺序', depth_background_first: '背景 → 前景', depth_foreground_first: '前景 → 背景', size_square: '1:1 · 1K', size_wide: '16:9 · 1K', sam2_local: 'SAM 2 本地', selection_needed: '请先在画布上框选或点击一个区域。', selection_confirmed: '区域已确定，接下来细化边缘。', matte_done: 'Matte Anything 细化完成。', foreground_done: '原图像素前景层已锁定。', nano_done: '背景补全层已准备，只作用于区域外。' };
const generationStrings = { generation_source_label: '生成输入层', generation_source_none: '先选择图层', generation_source_foreground: '已提取前景层', generation_source_reference: '参考图层', generation_source_needed: '请先提取并选择一个图层。', scene_preview: '查看场景图层', foreground_preview: '查看已提取前景层', foreground_visible: '正在查看已提取前景层。', sam2_failed: 'SAM 2 分割失败，请检查本地服务。' };
const t = key => generationStrings[key] || pipelineStrings[key] || Translations.GetString(key);

const state = { scene: null, reference: null, foreground: null, generationSource: '', activeLayer: 'scene', mask: null, maskHistory: [], maskRedo: [], selectionHistory: [], selectionRedo: [], brush: 'add', zoom: 1, fitScale: 1, panX: 0, panY: 0, selectionView: null, spaceDown: false, panning: false, tool: 'mask', composite: null, generated: null, selectionMode: 'box', selection: null, selectionArmed: true };
const sceneCanvas = document.querySelector('#scene-canvas');
const maskCanvas = document.querySelector('#mask-canvas');
const canvasContent = document.querySelector('#canvas-content');
const canvasStage = document.querySelector('#canvas-stage');
const sceneCtx = sceneCanvas.getContext('2d');
const maskCtx = maskCanvas.getContext('2d');
const $ = selector => document.querySelector(selector);
const toast = message => { const node = $('#toast'); node.textContent = message; node.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => node.classList.remove('show'), 2600); };

function hydrateText() {
  document.title = t('app_name');
  document.querySelectorAll('[data-i18n]').forEach(node => { node.textContent = t(node.dataset.i18n); });
  document.querySelectorAll('[data-i18n-aria]').forEach(node => { const label = t(node.dataset.i18nAria); node.setAttribute('aria-label', label); node.setAttribute('title', label); });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(node => { node.placeholder = t(node.dataset.i18nPlaceholder); });
}

function readImage(file) { return new Promise((resolve, reject) => { const url = URL.createObjectURL(file); const image = new Image(); image.onload = () => { URL.revokeObjectURL(url); resolve(image); }; image.onerror = reject; image.src = url; }); }
function fitCanvas(image) {
  clearGenerationSource();
  const max = 1800; const scale = Math.min(1, max / Math.max(image.naturalWidth, image.naturalHeight));
  sceneCanvas.width = Math.round(image.naturalWidth * scale); sceneCanvas.height = Math.round(image.naturalHeight * scale); maskCanvas.width = sceneCanvas.width; maskCanvas.height = sceneCanvas.height;
  sceneCtx.clearRect(0, 0, sceneCanvas.width, sceneCanvas.height); sceneCtx.drawImage(image, 0, 0, sceneCanvas.width, sceneCanvas.height); maskCtx.clearRect(0, 0, maskCanvas.width, maskCanvas.height);
  refreshFitScale();
}
function thumbnailData(image) { const canvas = document.createElement('canvas'); canvas.width = 96; canvas.height = Math.round(96 * image.naturalHeight / image.naturalWidth); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); return canvas.toDataURL('image/png'); }
function loadScene(image, name) { state.scene = image; state.mask = null; state.maskHistory = []; state.maskRedo = []; state.selectionHistory = []; state.selectionRedo = []; state.selection = null; state.selectionView = null; state.panX = 0; state.panY = 0; state.selectionArmed = true; fitCanvas(image); $('#empty-state').hidden = true; $('#canvas-hud').hidden = false; $('#selection-box').hidden = true; $('#scene-thumb').src = thumbnailData(image); $('#scene-name').textContent = name; $('#scene-meta').textContent = `${image.naturalWidth} × ${image.naturalHeight}`; $('#selection-chip').textContent = t('local_mode'); $('#coords-chip').textContent = `${sceneCanvas.width} × ${sceneCanvas.height} px`; $('#canvas-status').textContent = t('scene_loaded'); updateStep(1); updateHistoryButtons(); }
function loadReference(image, name) { state.reference = image; $('#reference-row').hidden = false; $('#reference-thumb').src = thumbnailData(image); $('#reference-name').textContent = name; $('#reference-meta').textContent = `${image.naturalWidth} × ${image.naturalHeight}`; toast(t('reference_loaded')); }
function syncGenerationSources() { const select = $('#generation-source'); if (!select) return; const foregroundOption = select.querySelector('[value="foreground"]'); const referenceOption = select.querySelector('[value="reference"]'); foregroundOption.disabled = !state.foreground; referenceOption.disabled = !state.reference; select.disabled = !state.foreground && !state.reference; if ((select.value === 'foreground' && !state.foreground) || (select.value === 'reference' && !state.reference)) select.value = ''; state.generationSource = select.value; }
function updateLayerRows() { $('#scene-row').classList.toggle('active', state.activeLayer === 'scene'); $('#foreground-row').classList.toggle('active', state.activeLayer === 'foreground'); }
function hideForegroundLayer() { $('#foreground-row').hidden = true; if (state.activeLayer === 'foreground') { state.activeLayer = 'scene'; if (state.scene) { sceneCtx.clearRect(0, 0, sceneCanvas.width, sceneCanvas.height); sceneCtx.drawImage(state.scene, 0, 0, sceneCanvas.width, sceneCanvas.height); drawMask(); } } updateLayerRows(); }
function showForegroundLayer() { if (!state.foreground) return; state.activeLayer = 'foreground'; state.tool = 'foreground'; sceneCtx.clearRect(0, 0, sceneCanvas.width, sceneCanvas.height); sceneCtx.drawImage(state.foreground, 0, 0); maskCtx.clearRect(0, 0, maskCanvas.width, maskCanvas.height); document.querySelectorAll('[data-tool]').forEach(button => button.classList.remove('active')); updateLayerRows(); $('#canvas-status').textContent = t('foreground_visible'); }
function showSceneLayer() { if (!state.scene) return; state.activeLayer = 'scene'; state.tool = 'mask'; sceneCtx.clearRect(0, 0, sceneCanvas.width, sceneCanvas.height); sceneCtx.drawImage(state.scene, 0, 0, sceneCanvas.width, sceneCanvas.height); drawMask(); document.querySelectorAll('[data-tool]').forEach(button => button.classList.toggle('active', button.dataset.tool === 'mask')); updateLayerRows(); }
function clearGenerationSource() { state.foreground = null; state.generationSource = ''; hideForegroundLayer(); syncGenerationSources(); }

function updateStep(step) { document.querySelectorAll('.step-list li').forEach(item => item.classList.toggle('active', Number(item.dataset.step) === step)); $('#step-count').textContent = `${step}/5`; }
function drawMask() { if (!state.mask) { maskCtx.clearRect(0, 0, maskCanvas.width, maskCanvas.height); return; } const imageData = maskCtx.createImageData(maskCanvas.width, maskCanvas.height); for (let i = 0; i < state.mask.length; i++) { if (state.mask[i]) { imageData.data[i * 4] = 22; imageData.data[i * 4 + 1] = 124; imageData.data[i * 4 + 2] = 114; imageData.data[i * 4 + 3] = 120; } } maskCtx.putImageData(imageData, 0, 0); }
function cloneMask(mask) { return mask ? mask.slice() : null; }
function updateHistoryButtons() { $('#undo-mask').disabled = state.maskHistory.length === 0 && state.selectionHistory.length === 0; $('#redo-mask').disabled = state.maskRedo.length === 0 && state.selectionRedo.length === 0; $('#delete-mask').disabled = !state.mask && !state.selection; }
function rememberMask() { state.maskHistory.push(cloneMask(state.mask)); if (state.maskHistory.length > 20) state.maskHistory.shift(); state.maskRedo = []; updateHistoryButtons(); }
function rememberSelection() { state.selectionHistory.push(state.selection ? { ...state.selection } : null); if (state.selectionHistory.length > 20) state.selectionHistory.shift(); state.selectionRedo = []; updateHistoryButtons(); }
function clearSelectionHistory() { state.selectionHistory = []; state.selectionRedo = []; updateHistoryButtons(); }
function renderSelection() { if (state.selection || state.selectionView) showSelection(state.selection); else $('#selection-box').hidden = true; }
function restoreMask(mask) { state.mask = cloneMask(mask); drawMask(); updateHistoryButtons(); }
function restoreSelection(selection) { state.selection = selection ? { ...selection } : null; state.selectionView = null; renderSelection(); updateHistoryButtons(); }
function undoMask() { if (state.selectionHistory.length) { state.selectionRedo.push(state.selection ? { ...state.selection } : null); restoreSelection(state.selectionHistory.pop()); toast(t('undo_done')); return; } if (!state.maskHistory.length) return; state.maskRedo.push(cloneMask(state.mask)); restoreMask(state.maskHistory.pop()); toast(t('undo_done')); }
function redoMask() { if (state.selectionRedo.length) { state.selectionHistory.push(state.selection ? { ...state.selection } : null); restoreSelection(state.selectionRedo.pop()); toast(t('redo_done')); return; } if (!state.maskRedo.length) return; state.maskHistory.push(cloneMask(state.mask)); restoreMask(state.maskRedo.pop()); toast(t('redo_done')); }
function deleteMask() { if (!state.mask && !state.selection) { $('#canvas-status').textContent = t('mask_cleared'); toast(t('mask_cleared')); return; } if (state.selection && !state.mask) rememberSelection(); else if (state.mask) rememberMask(); state.mask = null; state.foreground = null; state.selection = null; state.selectionView = null; $('#selection-box').hidden = true; drawMask(); $('#edge-quality').textContent = '—'; $('#quality-meter').style.width = '0'; $('#canvas-status').textContent = t('delete_done'); updateHistoryButtons(); }
function createMask(fill = false) { state.mask = new Uint8Array(maskCanvas.width * maskCanvas.height); if (fill) state.mask.fill(1); drawMask(); }
function localAutoMask(record = true) { if (!state.scene) { toast(t('no_scene')); return; } if (record) rememberMask(); createMask(); const pixels = sceneCtx.getImageData(0, 0, sceneCanvas.width, sceneCanvas.height).data; const horizon = Math.floor(sceneCanvas.height * .62); for (let y = 0; y < sceneCanvas.height; y++) for (let x = 0; x < sceneCanvas.width; x++) { const i = (y * sceneCanvas.width + x) * 4; const r = pixels[i], g = pixels[i + 1], b = pixels[i + 2]; const lower = y > horizon; const green = g > r * .82 && g > b * .92; const warm = r > b * 1.25 && g > b * 1.05; state.mask[y * maskCanvas.width + x] = lower && (green || warm) ? 1 : 0; } drawMask(); $('#edge-quality').textContent = '84%'; $('#quality-meter').style.width = '84%'; $('#canvas-status').textContent = t('mask_ready'); updateStep(2); updateHistoryButtons(); }
function canvasPoint(event) { const rect = sceneCanvas.getBoundingClientRect(); return { x: Math.max(0, Math.min(maskCanvas.width - 1, Math.round((event.clientX - rect.left) / rect.width * maskCanvas.width))), y: Math.max(0, Math.min(maskCanvas.height - 1, Math.round((event.clientY - rect.top) / rect.height * maskCanvas.height))) }; }
function stagePoint(event) { const rect = canvasStage.getBoundingClientRect(); return { x: event.clientX - rect.left, y: event.clientY - rect.top }; }
function showSelection(selection) { const box = $('#selection-box'); box.hidden = false; box.classList.toggle('point', state.selectionMode === 'point'); if (state.selectionView) { box.style.left = `${state.selectionView.x}px`; box.style.top = `${state.selectionView.y}px`; box.style.width = state.selectionMode === 'point' ? '' : `${Math.max(2, state.selectionView.w)}px`; box.style.height = state.selectionMode === 'point' ? '' : `${Math.max(2, state.selectionView.h)}px`; return; } const stage = canvasStage.getBoundingClientRect(); const canvas = sceneCanvas.getBoundingClientRect(); const scaleX = canvas.width / maskCanvas.width; const scaleY = canvas.height / maskCanvas.height; box.style.left = `${canvas.left - stage.left + selection.x * scaleX}px`; box.style.top = `${canvas.top - stage.top + selection.y * scaleY}px`; box.style.width = state.selectionMode === 'point' ? '' : `${Math.max(2, selection.w * scaleX)}px`; box.style.height = state.selectionMode === 'point' ? '' : `${Math.max(2, selection.h * scaleY)}px`; }
function updateSelectionFromView() { const view = state.selectionView; const stage = canvasStage.getBoundingClientRect(); const canvas = sceneCanvas.getBoundingClientRect(); const left = canvas.left - stage.left; const top = canvas.top - stage.top; const right = left + canvas.width; const bottom = top + canvas.height; const x1 = Math.max(view.x, left); const y1 = Math.max(view.y, top); const x2 = Math.min(view.x + view.w, right); const y2 = Math.min(view.y + view.h, bottom); if (x2 <= x1 || y2 <= y1) state.selection = null; else state.selection = { x: Math.round((x1 - left) / canvas.width * maskCanvas.width), y: Math.round((y1 - top) / canvas.height * maskCanvas.height), w: Math.round((x2 - x1) / canvas.width * maskCanvas.width), h: Math.round((y2 - y1) / canvas.height * maskCanvas.height) }; showSelection(state.selection); }
function canvasBlob(canvas) { return new Promise(resolve => canvas.toBlob(resolve, 'image/png')); }
async function decodeMask(base64, width, height) { const image = new Image(); image.src = `data:image/png;base64,${base64}`; await image.decode(); const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; const context = canvas.getContext('2d'); context.drawImage(image, 0, 0, width, height); const pixels = context.getImageData(0, 0, width, height).data; const mask = new Uint8Array(width * height); for (let i = 0; i < mask.length; i++) mask[i] = pixels[i * 4] > 127 ? 1 : 0; return mask; }
async function requestSam2(selection) { const form = new FormData(); form.append('file', await canvasBlob(sceneCanvas), 'scene.png'); if (state.selectionMode === 'box') form.append('box', `${selection.x},${selection.y},${selection.x + selection.w},${selection.y + selection.h}`); else { form.append('point_x', `${selection.x}`); form.append('point_y', `${selection.y}`); } const response = await fetch('http://127.0.0.1:8765/segment', { method: 'POST', body: form }); if (!response.ok) throw new Error(`SAM2 HTTP ${response.status}`); return response.json(); }
async function checkSam2() { const status = $('#sam2-status'); try { const response = await fetch('http://127.0.0.1:8765/health'); if (!response.ok) throw new Error('unavailable'); status.textContent = t('sam2_online'); } catch { status.textContent = t('sam2_offline'); } }
async function confirmSelection() { if (!state.scene) { $('#canvas-status').textContent = t('no_scene'); toast(t('no_scene')); return; } if (!state.selection) { state.selectionArmed = true; $('#canvas-status').textContent = t('selection_needed'); toast(t('selection_needed')); return; } const previousMask = cloneMask(state.mask); rememberMask(); try { const result = await requestSam2(state.selection); state.mask = await decodeMask(result.mask_base64, maskCanvas.width, maskCanvas.height); clearSelectionHistory(); state.selectionView = null; state.selectionArmed = false; drawMask(); $('#selection-chip').textContent = t('sam2_local'); $('#canvas-status').textContent = t('selection_confirmed'); updateStep(2); updateHistoryButtons(); return; } catch { state.mask = previousMask; drawMask(); state.selectionArmed = true; $('#canvas-status').textContent = t('sam2_failed'); toast(t('sam2_failed')); updateHistoryButtons(); return; } }
function refineMatte() { if (!state.mask) { $('#canvas-status').textContent = t('selection_needed'); toast(t('selection_needed')); return; } drawMask(); $('#edge-quality').textContent = '91%'; $('#quality-meter').style.width = '91%'; $('#canvas-status').textContent = t('matte_done'); updateStep(3); }
function extractForeground() { const foreground = buildTransparent(); if (!foreground) { $('#canvas-status').textContent = t('no_scene'); toast(t('no_scene')); return; } state.foreground = foreground; $('#foreground-thumb').src = foreground.toDataURL('image/png'); $('#foreground-meta').textContent = `${foreground.width} × ${foreground.height}`; $('#foreground-row').hidden = false; updateStep(4); showForegroundLayer(); }
async function repairBackground() { if (!state.scene || !state.mask) { $('#canvas-status').textContent = t('selection_needed'); toast(t('selection_needed')); return; } const selection = state.selection ? ` Selected region in source pixels: x=${state.selection.x}, y=${state.selection.y}, width=${state.selection.w || 1}, height=${state.selection.h || 1}.` : ''; const prompt = `${$('#nano-prompt').value.trim() || 'Edit only the selected background hole. Preserve the original foreground subject and lighting.'}${selection}`; try { const result = await runImageJob({ prompt, size: $('#generation-size').value, resolution: '1K', provider: $('#nano-provider').value }, [await imageBlob(state.scene)]); const encoded = result.result_b64_json; if (encoded) { const image = new Image(); image.onload = () => { state.backgroundImage = image; $('#canvas-status').textContent = t('nano_done'); updateStep(5); }; image.src = `data:image/png;base64,${encoded}`; return; } } catch (error) { if (error.message !== 'missing-api') toast(t('generation_failed')); } state.backgroundImage = null; $('#canvas-status').textContent = t('nano_done'); updateStep(5); }
function paintAt(event) { if (!state.mask) createMask(); const rect = sceneCanvas.getBoundingClientRect(); const x = Math.max(0, Math.min(maskCanvas.width - 1, Math.round((event.clientX - rect.left) / rect.width * maskCanvas.width))); const y = Math.max(0, Math.min(maskCanvas.height - 1, Math.round((event.clientY - rect.top) / rect.height * maskCanvas.height))); const radius = Number($('#brush-size').value) / 2; const minX = Math.max(0, Math.floor(x - radius)), maxX = Math.min(maskCanvas.width - 1, Math.ceil(x + radius)); const minY = Math.max(0, Math.floor(y - radius)), maxY = Math.min(maskCanvas.height - 1, Math.ceil(y + radius)); for (let py = minY; py <= maxY; py++) for (let px = minX; px <= maxX; px++) if ((px - x) ** 2 + (py - y) ** 2 <= radius ** 2) state.mask[py * maskCanvas.width + px] = state.brush === 'add' ? 1 : 0; drawMask(); }
function buildTransparent() { if (!state.scene) return null; if (!state.mask) localAutoMask(false); const output = document.createElement('canvas'); output.width = sceneCanvas.width; output.height = sceneCanvas.height; const ctx = output.getContext('2d'); ctx.drawImage(state.scene, 0, 0, output.width, output.height); const pixels = ctx.getImageData(0, 0, output.width, output.height); for (let i = 0; i < state.mask.length; i++) pixels.data[i * 4 + 3] = state.mask[i] ? 255 : 0; ctx.putImageData(pixels, 0, 0); return output; }
function downloadCanvas(canvas, filename) { canvas.toBlob(blob => { const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = filename; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 500); }); }
function compositeCanvas() { const asset = buildTransparent(); if (!asset) return null; const output = document.createElement('canvas'); output.width = sceneCanvas.width; output.height = sceneCanvas.height; const ctx = output.getContext('2d'); const background = state.backgroundImage || state.scene; const drawBackground = () => ctx.drawImage(background, 0, 0, output.width, output.height); const drawForeground = () => { ctx.globalAlpha = Number($('#opacity').value) / 100; ctx.globalCompositeOperation = $('#blend-mode').value; ctx.drawImage(asset, 0, 0); ctx.globalCompositeOperation = 'source-over'; ctx.globalAlpha = 1; }; if ($('#depth-order').value === 'foreground,background') { drawForeground(); drawBackground(); } else { drawBackground(); drawForeground(); } return output; }
function renderCompositePreview() { const output = compositeCanvas(); if (!output) return; state.composite = output; sceneCtx.clearRect(0, 0, sceneCanvas.width, sceneCanvas.height); sceneCtx.drawImage(output, 0, 0); maskCtx.clearRect(0, 0, maskCanvas.width, maskCanvas.height); $('#canvas-status').textContent = t('composite_done'); updateStep(4); }
async function apiFetch(path, options = {}) { const base = ($('#api-base').value || 'http://localhost:8080/').trim().replace(/\/$/, ''); const key = ($('#api-key').value || '').trim(); if (!base || !key) throw new Error('missing-api'); const headers = new Headers(options.headers || {}); headers.set('Authorization', `Bearer ${key}`); const response = await fetch(`${base}/${path.replace(/^\//, '')}`, { ...options, headers }); if (!response.ok) throw new Error(`HTTP ${response.status}`); return response; }
async function pollJob(jobId) { for (;;) { const response = await apiFetch(`/api/images/jobs/${jobId}`); const job = await response.json(); if (job.status === 'completed') return (await apiFetch(`/api/images/jobs/${jobId}/result`)).json(); if (job.status === 'failed') throw new Error(job.error_message || 'job-failed'); await new Promise(resolve => setTimeout(resolve, 1000)); } }
async function runImageJob(fields, references = []) { const form = new FormData(); Object.entries(fields).forEach(([key, value]) => form.append(key, value)); references.forEach((blob, index) => form.append('reference_files', blob, `reference-${index}.png`)); const accepted = await (await apiFetch('/api/images', { method: 'POST', body: form })).json(); return pollJob(accepted.id); }
async function runChatJob(text) { const accepted = await (await apiFetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) })).json(); return pollJob(accepted.id); }
function imageBlob(image) { const canvas = document.createElement('canvas'); canvas.width = image.naturalWidth; canvas.height = image.naturalHeight; canvas.getContext('2d').drawImage(image, 0, 0); return new Promise(resolve => canvas.toBlob(resolve, 'image/png')); }
async function generateImage() { const prompt = $('#generation-prompt').value.trim(); const source = state.generationSource === 'foreground' ? state.foreground : state.generationSource === 'reference' ? state.reference : null; if (!source) { $('#canvas-status').textContent = t('generation_source_needed'); toast(t('generation_source_needed')); return; } if (!prompt) { $('#canvas-status').textContent = t('prompt_label'); toast(t('prompt_label')); return; } $('#generate-image').disabled = true; $('#generate-image span:last-child').textContent = t('generating'); try { const reference = state.generationSource === 'foreground' ? await canvasBlob(state.foreground) : await imageBlob(source); const result = await runImageJob({ prompt, size: $('#generation-size').value, resolution: '1K', provider: $('#nano-provider').value }, [reference]); const url = result.result_b64_json ? `data:image/png;base64,${result.result_b64_json}` : result.image_url; if (!url) throw new Error('empty'); const image = new Image(); image.onload = () => { state.generated = image; $('#generated-image').src = url; $('#generated-preview').hidden = false; toast(t('generation_done')); updateStep(4); }; image.src = url; } catch (error) { const message = error.message === 'missing-api' ? t('api_missing') : t('generation_failed'); $('#canvas-status').textContent = message; toast(message); } finally { $('#generate-image').disabled = false; $('#generate-image span:last-child').textContent = t('generate_image'); } }
async function sendChat() { const input = $('#chat-input'); const prompt = input.value.trim(); if (!prompt) { toast(t('prompt_label')); return; } const log = $('#chat-log'); const userBubble = document.createElement('div'); userBubble.className = 'chat-bubble user'; userBubble.textContent = prompt; log.appendChild(userBubble); input.value = ''; const thinking = document.createElement('div'); thinking.className = 'chat-bubble assistant'; thinking.textContent = t('thinking'); log.appendChild(thinking); log.scrollTop = log.scrollHeight; try { const result = await runChatJob(prompt); thinking.textContent = result.text || t('chat_failed'); } catch (error) { thinking.textContent = error.message === 'missing-api' ? t('api_missing') : t('chat_failed'); } log.scrollTop = log.scrollHeight; }
function saveWorkspace() { localStorage.setItem('pinta-ai-asset-workbench', JSON.stringify({ prompt: $('#generation-prompt').value, apiBase: $('#api-base').value, zoom: state.zoom })); toast(t('saved')); }
function loadWorkspace() { try { const data = JSON.parse(localStorage.getItem('pinta-ai-asset-workbench') || '{}'); $('#generation-prompt').value = data.prompt || ''; $('#api-base').value = data.apiBase || ''; if (data.zoom) setZoom(data.zoom); } catch { /* ignore malformed local state */ } }
function refreshFitScale() { if (!sceneCanvas.width) return; const widthScale = (canvasStage.clientWidth - 28) / sceneCanvas.width; const heightScale = (canvasStage.clientHeight - 28) / sceneCanvas.height; state.fitScale = Math.max(.1, Math.min(1, widthScale, heightScale)); setZoom(state.zoom); }
function applyPan() { canvasContent.style.transform = `translate3d(${state.panX}px, ${state.panY}px, 0)`; }
function setZoom(value) { state.zoom = Math.max(.25, Math.min(4, value)); $('#zoom-label').textContent = `${Math.round(state.zoom * 100)}%`; if (sceneCanvas.width) { const scale = state.fitScale * state.zoom; canvasContent.style.width = `${Math.max(1, Math.round(sceneCanvas.width * scale))}px`; canvasContent.style.height = `${Math.max(1, Math.round(sceneCanvas.height * scale))}px`; sceneCanvas.style.width = '100%'; sceneCanvas.style.height = '100%'; maskCanvas.style.width = '100%'; maskCanvas.style.height = '100%'; applyPan(); renderSelection(); } }
function zoomAt(value, clientX, clientY) { const before = canvasContent.getBoundingClientRect(); const anchorX = clientX - before.left; const anchorY = clientY - before.top; const oldZoom = state.zoom; setZoom(value); const ratio = state.zoom / oldZoom; const after = canvasContent.getBoundingClientRect(); state.panX += clientX - (after.left + anchorX * ratio); state.panY += clientY - (after.top + anchorY * ratio); applyPan(); renderSelection(); }

function bindLayerRow(selector, action) { const row = $(selector); row.addEventListener('click', event => { if (!event.target.closest('button')) action(); }); row.addEventListener('keydown', event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); action(); } }); }

function bind() {
  $('#scene-input').addEventListener('change', async event => { const file = event.target.files[0]; if (file) loadScene(await readImage(file), file.name); });
  $('#reference-input').addEventListener('change', async event => { const file = event.target.files[0]; if (file) loadReference(await readImage(file), file.name); });
  $('#load-demo').addEventListener('click', async () => { const image = await readImage(await fetch('assets/scene.png').then(response => response.blob())); loadScene(image, 'scene.png'); toast(t('demo_loaded')); });
  $('#clear-scene').addEventListener('click', () => { state.scene = null; state.mask = null; state.maskHistory = []; state.maskRedo = []; state.selection = null; state.selectionView = null; state.selectionHistory = []; state.selectionRedo = []; sceneCtx.clearRect(0, 0, sceneCanvas.width, sceneCanvas.height); maskCtx.clearRect(0, 0, maskCanvas.width, maskCanvas.height); $('#empty-state').hidden = false; $('#canvas-hud').hidden = true; $('#canvas-status').textContent = t('no_scene'); renderSelection(); updateHistoryButtons(); toast(t('no_scene')); });
  $('#clear-reference').addEventListener('click', () => { state.reference = null; $('#reference-row').hidden = true; });
  document.querySelectorAll('[data-selection]').forEach(button => button.addEventListener('click', () => { state.selectionMode = button.dataset.selection; state.selection = null; state.selectionView = null; clearSelectionHistory(); state.selectionArmed = true; document.querySelectorAll('[data-selection]').forEach(item => item.classList.toggle('active', item === button)); renderSelection(); }));
  $('#sam2-select').addEventListener('click', confirmSelection); $('#matte-refine').addEventListener('click', refineMatte); $('#extract-foreground').addEventListener('click', extractForeground); $('#nano-repair').addEventListener('click', repairBackground);
  $('#auto-isolate').addEventListener('click', localAutoMask); $('#clear-mask').addEventListener('click', deleteMask); $('#delete-mask').addEventListener('click', deleteMask); $('#undo-mask').addEventListener('click', undoMask); $('#redo-mask').addEventListener('click', redoMask);
  $('#invert-mask').addEventListener('click', () => { if (!state.scene) { $('#canvas-status').textContent = t('no_scene'); toast(t('no_scene')); return; } rememberMask(); if (!state.mask) createMask(true); state.mask = Uint8Array.from(state.mask, value => value ? 0 : 1); drawMask(); toast(t('mask_inverted')); updateHistoryButtons(); });
  document.querySelectorAll('[data-brush]').forEach(button => button.addEventListener('click', () => { state.brush = button.dataset.brush; document.querySelectorAll('[data-brush]').forEach(item => item.classList.toggle('active', item === button)); }));
  document.querySelectorAll('[data-tool]').forEach(button => button.addEventListener('click', () => { state.tool = button.dataset.tool; document.querySelectorAll('[data-tool]').forEach(item => item.classList.toggle('active', item === button)); if (state.tool === 'compare' && state.scene && state.composite) { sceneCtx.clearRect(0, 0, sceneCanvas.width, sceneCanvas.height); sceneCtx.drawImage(state.scene, 0, 0); } else if (state.tool === 'composite') renderCompositePreview(); }));
  $('#brush-size').addEventListener('input', event => { $('#brush-size-value').textContent = `${event.target.value} px`; }); $('#feather').addEventListener('input', event => { $('#feather-value').textContent = `${event.target.value} px`; }); $('#opacity').addEventListener('input', event => { $('#opacity-value').textContent = `${event.target.value}%`; if (state.tool === 'composite') renderCompositePreview(); }); $('#blend-mode').addEventListener('change', () => { if (state.tool === 'composite') renderCompositePreview(); }); $('#depth-order').addEventListener('change', () => { if (state.tool === 'composite') renderCompositePreview(); });
  let drawing = false; let selecting = false; let selectionStart = null; let panStart = null;
  canvasStage.addEventListener('wheel', event => { event.preventDefault(); zoomAt(state.zoom + (event.deltaY < 0 ? .1 : -.1), event.clientX, event.clientY); }, { passive: false });
  canvasStage.addEventListener('pointerdown', event => { if (event.button !== 1 && !state.spaceDown) return; event.preventDefault(); state.panning = true; panStart = { x: event.clientX, y: event.clientY, panX: state.panX, panY: state.panY }; canvasStage.classList.add('is-panning'); canvasStage.setPointerCapture(event.pointerId); }, true);
  canvasStage.addEventListener('pointermove', event => { if (!state.panning) return; state.panX = panStart.panX + event.clientX - panStart.x; state.panY = panStart.panY + event.clientY - panStart.y; applyPan(); });
  canvasStage.addEventListener('pointerdown', event => { if (event.target.closest('.empty-state, .canvas-hud')) return; if (state.panning || state.tool !== 'mask' || !state.selectionArmed || event.button !== 0) return; event.preventDefault(); rememberSelection(); const point = stagePoint(event); state.selectionView = state.selectionMode === 'point' ? { x: point.x - 8, y: point.y - 8, w: 16, h: 16 } : { x: point.x, y: point.y, w: 0, h: 0 }; if (state.selectionMode === 'point') { updateSelectionFromView(); return; } selecting = true; selectionStart = point; canvasStage.setPointerCapture(event.pointerId); updateSelectionFromView(); }, true);
  canvasStage.addEventListener('pointermove', event => { if (!selecting || !selectionStart || !canvasStage.hasPointerCapture(event.pointerId)) return; const point = stagePoint(event); state.selectionView = { x: Math.min(selectionStart.x, point.x), y: Math.min(selectionStart.y, point.y), w: Math.abs(point.x - selectionStart.x), h: Math.abs(point.y - selectionStart.y) }; updateSelectionFromView(); });
  const stopSelecting = event => { if (!selecting) return; selecting = false; if (state.selection?.w < 4 || state.selection?.h < 4) state.selection = null; renderSelection(); if (canvasStage.hasPointerCapture(event.pointerId)) canvasStage.releasePointerCapture(event.pointerId); updateHistoryButtons(); };
  canvasStage.addEventListener('pointerup', stopSelecting); canvasStage.addEventListener('pointercancel', stopSelecting);
  const stopPanning = event => { if (!state.panning) return; state.panning = false; panStart = null; canvasStage.classList.remove('is-panning'); if (canvasStage.hasPointerCapture(event.pointerId)) canvasStage.releasePointerCapture(event.pointerId); };
  canvasStage.addEventListener('pointerup', stopPanning); canvasStage.addEventListener('pointercancel', stopPanning);
  document.addEventListener('keydown', event => { const editing = /INPUT|TEXTAREA|SELECT/.test(event.target.tagName); if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'z' && !editing) { event.preventDefault(); event.shiftKey ? redoMask() : undoMask(); return; } if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'y' && !editing) { event.preventDefault(); redoMask(); return; } if (event.key === 'Delete' && !editing) { event.preventDefault(); deleteMask(); return; } if (event.code === 'Space' && !editing) { state.spaceDown = true; event.preventDefault(); } });
  document.addEventListener('keyup', event => { if (event.code === 'Space') state.spaceDown = false; });
  sceneCanvas.addEventListener('pointerdown', event => { if (state.panning || state.tool !== 'mask' || state.selectionArmed) return; rememberMask(); drawing = true; sceneCanvas.setPointerCapture(event.pointerId); paintAt(event); }); sceneCanvas.addEventListener('pointermove', event => { if (drawing) paintAt(event); }); sceneCanvas.addEventListener('pointerup', () => { drawing = false; updateHistoryButtons(); });
  $('#zoom-out').addEventListener('click', () => setZoom(state.zoom - .1)); $('#zoom-in').addEventListener('click', () => setZoom(state.zoom + .1)); $('#reset-view').addEventListener('click', () => { state.panX = 0; state.panY = 0; setZoom(1); }); window.addEventListener('resize', refreshFitScale);
  $('#export-png').addEventListener('click', () => { const asset = buildTransparent(); if (asset) { downloadCanvas(asset, 'isolated-asset.png'); toast(t('exported')); } else toast(t('no_scene')); }); $('#composite-export').addEventListener('click', () => { const output = compositeCanvas(); if (output) { downloadCanvas(output, 'recomposed-scene.png'); toast(t('composite_done')); } else toast(t('no_scene')); });
  $('#generate-image').addEventListener('click', generateImage); $('#use-generated').addEventListener('click', () => { if (state.generated) loadReference(state.generated, 'generated-reference.png'); }); $('#send-chat').addEventListener('click', sendChat); $('#chat-input').addEventListener('keydown', event => { if (event.key === 'Enter' && (event.ctrlKey || event.metaKey)) sendChat(); }); $('#save-workspace').addEventListener('click', saveWorkspace); $('#settings-toggle').addEventListener('click', () => { $('#settings-body').hidden = !$('#settings-body').hidden; });
  $('#generation-source').addEventListener('change', event => { state.generationSource = event.target.value; });
  bindLayerRow('#scene-row', showSceneLayer);
  bindLayerRow('#foreground-row', showForegroundLayer);
  $('#reference-input').addEventListener('change', syncGenerationSources);
  $('#clear-reference').addEventListener('click', syncGenerationSources);
  $('#use-generated').addEventListener('click', syncGenerationSources);
  $('#extract-foreground').addEventListener('click', syncGenerationSources);
  $('#clear-mask').addEventListener('click', syncGenerationSources);
  $('#delete-mask').addEventListener('click', syncGenerationSources);
  $('#clear-mask').addEventListener('click', hideForegroundLayer);
  $('#delete-mask').addEventListener('click', hideForegroundLayer);
  $('#clear-scene').addEventListener('click', clearGenerationSource);
}

hydrateText(); loadWorkspace(); bind(); syncGenerationSources(); updateHistoryButtons(); checkSam2();
