<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Install GTK library dependencies on Windows, from the MSYS installation. -->
  <PropertyGroup>
    <!-- Note this can be overridden by an environment variable with the same name. -->
    <MinGWFolder>C:\msys64\clang64</MinGWFolder>
    <MinGWBinFolder>$(MinGWFolder)\bin</MinGWBinFolder>
    <!-- Skip bundling when MSYS2/MinGW is not installed (e.g. dev machines without the runtime toolchain). -->
    <BundleGtk Condition="Exists('$(MinGWFolder)')">true</BundleGtk>
    <BundleGtk Condition=" '$(BundleGtk)' == '' ">false</BundleGtk>
  </PropertyGroup>

  <ItemGroup>
    <!-- Library link dependencies (run `ldd libadwaita-1-0.dll | grep '\/mingw.*\.dll' -o`) -->
    <!-- TODO - This should be improved in the future to be more automated -->
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libadwaita-1-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libappstream-5.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libbrotlicommon.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libbrotlidec.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libbz2-1.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libcairo-2.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libcairo-gobject-2.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libcairo-script-interpreter-2.dll" />
    <!-- Match against the arch-specific suffix, e.g. libcrypto-3-x64.dll -->
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libcrypto-3*.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libcurl-4.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libc++.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libdatrie-1.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libdeflate.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libepoxy-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libexpat-1.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libffi-8.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libfontconfig-1.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libfreetype-6.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libfribidi-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libfyaml-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libgdk_pixbuf-2.0-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libgio-2.0-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libglib-2.0-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libgmodule-2.0-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libgobject-2.0-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libgraphene-1.0-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libgraphite2.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libgst*.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libgtk-4-1.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libharfbuzz-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libharfbuzz-subset-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libiconv-2.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libidn2-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libintl-8.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libjbig-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libjpeg-8.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\liblerc.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\liblzma-5.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\liblzo2-2.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libnghttp2-14.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libnghttp3-9.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libngtcp2-16.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libngtcp2_crypto_ossl-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\liborc-*.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libpango-1.0-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libpangocairo-1.0-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libpangoft2-1.0-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libpangowin32-1.0-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libpcre2-8-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libpixman-1-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libpng16-16.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libpsl-5.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libsharpyuv-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libssh2-1.dll" />
    <!-- Match against the arch-specific suffix, e.g. libssl-3-x64.dll -->
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libssl-3*.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libthai-0.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libtiff-6.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libunistring-5.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libunwind.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libwinpthread-1.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libwebp-7.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libxml2-16.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libxmlb-2.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libzstd.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\zlib1.dll" />

    <!-- Additional dependencies for the SVG pixbuf loader. -->
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libcharset-1.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\librsvg-2-2.dll" />

    <!-- Additional dependencies for the webp pixbuf loader. -->
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libwebp-7.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libwebpdemux-2.dll" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\libwebpmux-3.dll" />

    <!-- Package the Vulkan DLL (https://gitlab.gnome.org/GNOME/gtk/-/issues/7214) -->
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\vulkan-1.dll" />

    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\gdbus.exe" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\gdk-pixbuf-query-loaders.exe" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\gspawn-win64-helper.exe" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\gspawn-win64-helper-console.exe" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\gtk4-query-settings.exe" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWBinFolder)\gtk4-update-icon-cache.exe" />

    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWFolder)\lib\gdk-pixbuf-2.0\**" LinkBase="..\lib\gdk-pixbuf-2.0" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWFolder)\share\glib-2.0\schemas\**" LinkBase="..\share\glib-2.0\schemas" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWFolder)\share\locale\**" LinkBase="..\share\locale" />
    <GtkFile Condition="'$(BundleGtk)' == 'true'" Include="$(MinGWFolder)\share\icons\Adwaita\**" LinkBase="..\share\icons\Adwaita" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="@(GtkFile)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
